# spring
spring.main.banner-mode=off
spring.web.error.path=/public/error

# ecuacion
jp.ecuacion.locale.use-root=true
jp.ecuacion.splib.web.home-page=public/show/page?id=home
jp.ecuacion.splib.web.navbar.default-page-path=/public/show/page?id=home
jp.ecuacion.splib.web.bootstrap.is-background-gradient=true
