# spring
spring.thymeleaf.cache=true

# ecuacion
jp.ecuacion.splib.web.body.background-color=#ffffff
#jp.ecuacion.splib.web.body.background-image=linear-gradient(#abcdef, white)
#jp.ecuacion.splib.web.navbar.background-color-class=bg-secondary
jp.ecuacion.work-dir=/opt/data/work/ecuacion-references-splib-web-tutorial

# app
app.work-dir=/opt/data/files/ecuacion-references-splib-web-tutorial/work
