SystemCommon.createAccId=create acc ID
systemCommon.createAccId=create acc ID
SystemCommon.createTime=create time
systemCommon.createTime=create time
SystemCommon.lstUpdAccId=last-update user ID
systemCommon.lstUpdAccId=last-update user ID
SystemCommon.lstUpdTime=last-update time
systemCommon.lstUpdTime=last-update time
SystemCommon.isDeleted=is deleted
systemCommon.isDeleted=is deleted
SystemCommon.version=db update version
systemCommon.version=db update version
YourName.id=ID
yourName.id=ID
YourName.name=your name
yourName.name=your name
Book.id=ID
book.id=ID
Book.name=book name
book.name=book name
BookRentalStatus.bookId=book ID
bookRentalStatus.bookId=book ID
BookRentalStatus.status=status
bookRentalStatus.status=status
