# spring
spring.main.banner-mode=off
spring.profiles.active=profile
server.error.path=/public/error

# ecuacion
jp.ecuacion.splib.web.home-page=public/home
jp.ecuacion.splib.web.navbar.title=ecuacion-lib reference
jp.ecuacion.splib.web.navbar.default-page-path=/public/home
jp.ecuacion.splib.web.bootstrap.is-background-gradient=true
jp.ecuacion.splib.web.process-result-message.shown-at-each-item=true
jp.ecuacion.splib.web.process-result-message.shown-at-the-top=false

# app
