# spring

spring.main.banner-mode=off
spring.thymeleaf.cache=false
server.tomcat.max-part-count=100

## message files
spring.messages.basename=messages,strings

## max of upload file size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.max-http-request-header-size=15MB

## page transition
server.error.path=/public/error

# app



