# spring
spring.main.banner-mode=off
spring.thymeleaf.cache=false
server.error.path=/public/error

## message files
spring.messages.basename=messages,strings

## file upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.max-http-request-header-size=15MB
server.tomcat.max-part-count=100

# ecuacion
jp.ecuacion.splib.web.home-page=public/show/page?id=home
jp.ecuacion.splib.web.navbar.title=ecuacion-splib-web tutorial
jp.ecuacion.splib.web.navbar.default-page-path=/public/show/page?id=home
jp.ecuacion.splib.web.bootstrap.is-background-gradient=true
jp.ecuacion.splib.web.process-result-message.shown-at-each-item=true
jp.ecuacion.splib.web.process-result-message.shown-at-the-top=false

# app
