# greeting
greeting.firstName=あなたの名前
greeting.lastName=あなたの苗字
greeting.message=メッセージ
greeting.explanatoryFirstName=ご家族で共通ではないあなた固有の名前部分

# input
input.inputText=inputText
input.inputTakenPhotoMobile=inputTakenPhotoMobile
