# spring

# thymeleaf cannot seem to read from this file... Moved to application.properties
#spring.thymeleaf.cache=true

# ecuacion libraries

app.html.body.backgroundColor=#abcdef
jp.ecuacion.work-dir=./target/tmp

# app
