<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>ecuacion-references-splib-web-base</artifactId>
	<packaging>jar</packaging>
	<parent>
		<groupId>jp.ecuacion.references</groupId>
		<artifactId>ecuacion-references-parent</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<relativePath>..</relativePath>
	</parent>
	<properties>
		<!-- checkstyle is skipped in base projects -->
		<checkstyle.skip>true</checkstyle.skip>
	</properties>

	<dependencies>

		<!-- ecuacion-splib -->
		<dependency>
			<groupId>jp.ecuacion.splib</groupId>
			<artifactId>ecuacion-splib-jpa</artifactId>
		</dependency>

		<!-- DB driver -->
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
		</dependency>

	</dependencies>
</project>
