# spring

# thymeleaf cannot seem to read from this file... Moved to application.properties
#spring.thymeleaf.cache=true

# ecuacion libraries

app.html.body.backgroundColor=#ffffff
jp.ecuacion.work-dir=/opt/data/work/ecuacion-references-splib-web-tutorial

# app
