# spring
spring.main.banner-mode=off
spring.profiles.active=profile
spring.web.error.path=/public/error

## file upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.max-http-request-header-size=15MB
server.tomcat.max-part-count=100

# ecuacion
jp.ecuacion.locale.use-root=true
jp.ecuacion.splib.web.home-page=public/show/page?id=home
jp.ecuacion.splib.web.navbar.title=ecuacion spring library web : tutorial
jp.ecuacion.splib.web.navbar.default-page-path=/public/show/page?id=home
jp.ecuacion.splib.web.bootstrap.is-background-gradient=true
jp.ecuacion.splib.web.process-result-message.shown-at-each-item=true
jp.ecuacion.splib.web.process-result-message.shown-at-the-top=false

# app
app.work-dir=./target/tmp
