# greeting
greeting.firstName=あなたの名前
greeting.lastName=あなたの苗字
greeting.message=メッセージ
greeting.explanatoryFirstName=ご家族で共通ではないあなた固有の名前部分

# input
#input.inputText=inputText
#input.inputTakenPhotoMobile=inputTakenPhotoMobile

yourName.lstUpdTime=最終更新日時
book.lstUpdTime=最終更新日時
book.lstUpdAccId=最終更新者
bookRentalStatus.lstUpdTime=最終更新日時
bookRentalStatus.lstUpdAccId=最終更新者
