# spring
spring.main.banner-mode=off
spring.profiles.active=profile
spring.web.error.path=/public/error

# ecuacion
jp.ecuacion.locale.use-root=true
jp.ecuacion.splib.web.home-page=public/localeHome
jp.ecuacion.splib.web.navbar.title=ecuacion-tools reference
jp.ecuacion.splib.web.navbar.default-page-path=/public/localeHome
jp.ecuacion.splib.web.bootstrap.is-background-gradient=true
jp.ecuacion.splib.web.process-result-message.shown-at-each-item=true
jp.ecuacion.splib.web.process-result-message.shown-at-the-top=false

# app
